apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pgbouncer.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "pgbouncer.chart" . }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4}}
    {{- end }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pgbouncer.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pgbouncer.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.spec.labels }}
        {{- toYaml .Values.spec.labels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/ini: {{ include "pgbouncer.ini.1.0.0" . | sha256sum }}
        checksum/users: {{ include "userlist.txt.1.0.0" . | sha256sum }}
        {{- if .Values.spec.annotations }}
        {{- /* Using toJson instead of toYaml due to https://github.com/helm/helm/issues/3470  */ -}}
        {{- tpl (toJson .Values.spec.annotations) . | fromJson | toYaml |  nindent 8 }}
        {{- end }}
        {{- if .Values.prometheusExporter.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{ .Values.prometheusExporter.port | quote }}
        {{- end }}
    spec:
      affinity:
        {{- if eq .Values.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "pgbouncer.fullname" . }}
                  app.kubernetes.io/instance: {{ .Release.Name }}
        {{- else if eq .Values.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ include "pgbouncer.fullname" . }}
                    app.kubernetes.io/instance: {{ .Release.Name }}
        {{- end }}
        {{- if .Values.nodeAffinity }}
        nodeAffinity:
          {{- toYaml .Values.nodeAffinity | nindent 10 }}
        {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      {{- end }}
      volumes:
        - name: secret
          secret:
            secretName: {{ include "pgbouncer.fullname" . }}-secret
      containers:
        - name: pgbouncer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pgbouncer
              containerPort: {{ .Values.internalPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.internalPort }}
          lifecycle:
            preStop:
              exec:
                # https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/
                command: ["/bin/sh","-c","sleep 5"]
          volumeMounts:
            - name: secret
              subPath: userlist.txt
              mountPath: /etc/pgbouncer/userlist.txt
              readOnly: true
            - name: secret
              subPath: pgbouncer.ini
              mountPath: /etc/pgbouncer/pgbouncer.ini
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.prometheusExporter.enabled }}
        - name: pgbouncer-prometheus-exporter
          image: {{ .Values.prometheusExporter.image.repository }}:{{ .Values.prometheusExporter.image.tag }}
          imagePullPolicy: {{ .Values.prometheusExporter.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.prometheusExporter.port }}
          env:
            - name: PGBOUNCER_EXPORTER_HOST
              value: "0.0.0.0"
            - name: PGBOUNCER_EXPORTER_PORT
              value: {{ .Values.prometheusExporter.port | quote }}
            - name: PGBOUNCER_PORT
              value: {{ .Values.internalPort | quote }}
            - name: PGBOUNCER_USER
              value: {{ .Values.prometheusExporter.user | quote }}
            - name: PGBOUNCER_PASS
              value: {{ .Values.prometheusExporter.pass | quote }}

          resources: {{ toYaml .Values.prometheusExporter.resources | nindent 12 }}
        {{- end }}

