apiVersion: v1
kind: Service
metadata:
  name: {{ template "pgbouncer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "pgbouncer.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "pgbouncer.chart" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.internalPort }}
      targetPort: {{ .Values.internalPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "pgbouncer.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}